### ISSUE TITLE
Which coordinate system?

### ISSUE THREAD

**Issue by paulheinr** [kit-algo/InertialFlowCutter#14]
Hi,

is there any requirement for the coordinate system? Since the algorithm expects latitude and longitude, I assume spherical coordinates are required (like WGS84). Is that correct? 

Thanks in advance!

**Comment by larsgottesbueren** [comment]
In the internals, we use Euclidean. At least the projection code suggests as much. The names lat/lon are probably relics of old code. No guarantees though, it's been quite a while since I've looked at this.

**Comment by paulheinr** [comment]
Alright, thank you!
