### ISSUE TITLE
InertialFlowCutter for random network

### ISSUE THREAD

**Issue by rahelehzarei** [kit-algo/InertialFlowCutter#7]
Hi

how can I use InertialFlowCutter to order nodes of a random generate graph (it's not a map that contains latitude and longitude created by SUMO (Simulation of Urban Mobility))

Thanks

**Comment by larsgottesbueren** [comment]
Hi,

InertialFlowCutter is explicitly designed for road graphs (which come with coordinates). They don't have to be lat/long, any 2D coords should work. I think we don't do any stuff that relies on certain value ranges (not 100% sure though). If you have something grid-like or an embedding of some sort, that should work.
If not, you can still use plain FlowCutter, which doesn't need any coordinates but is somewhat slower.

Could you elaborate on your application?

Best,
Lars

**Comment by larsgottesbueren** [comment]
Closing, since no further response.
