### ISSUE TITLE
RoutingKit first_out

### ISSUE THREAD

**Issue by rahelehzarei** [kit-algo/InertialFlowCutter#8]
Hi
Is there any functionality available that creat RoutingKit first_out, head, travel_time, latitude and longitude file?

Thanks

**Comment by larsgottesbueren** [comment]
Hi, 

in the console you'll find the commands {load,save}\_routingkit\_{unweighted_graph, arc_weight, latitude, longitude}.
We have a 'global' graph that we're currently working on, and these commands always relate to that graph.
They take a filename argument to either load or save the corresponding vector.
The console is a binary executable that you can either start in interactive mode via 
```shell
./console interactive
```
and then type all of the commands you want to execute (has completion).
Or just run
```shell
./console cmd1 cmd2 ...
```
i.e. concatenate all of the commands you want to run.
If you want to know more about the available commands, take a look at src/console.cpp or try the auto-complete.
In our experimental setup, we actually just concatenate console commands, so take a look at those scripts, if you want to automize stuff.

Hope that helps.
Best,
Lars

**Comment by rahelehzarei** [comment]
Thanks Lars, It was very helpful.
I am actually reading the paper related to this repository and also Customizable Contraction Hierarchy. I would like to get a node ordering(as mentioned in CCH, KaIPH, and nested dissection on top of it). I was wondering how the option reorder_nodes_in_kahip2_nested_dissection_order in ./build/consol works.  I see a list of node-reordering tools that I'm not sure how they could be used. Are they working on an existing order file?

Thanks
Raheleh

**Comment by larsgottesbueren** [comment]
No they don't.
They directly permutate the 'global' graph.
You can save the ordering by calling
```shell
save_routingkit_node_permutation_since_last_load my_nd_order.bin
```
in the console, which you can then plug into RoutingKit like so

```shell
std::vector<unsigned> node_order = RoutingKit::load_vector<unsigned>("my_nd_order.bin");
RoutingKit::CustomizableContractionHierarchy cch(node_order, tail, head);
```

**Comment by rahelehzarei** [comment]
yeah, that is exactly my question, what is this 'global' graph? 
I am using different node ordering in RoutingKit and get the results. That's fine, I don't have any problem with that.

**Comment by larsgottesbueren** [comment]
Please just take a look at the experiment scripts we provide.
For example https://github.com/kit-algo/InertialFlowCutter/blob/master/evaluation/kahip_order.py for KaHiP.
You should be able to use them directly for computing orders.

Now for the 'global' graph.
In the console we have two static variables 
```cpp
ArrayIDIDFunc tail, head;
```
representing a graph.
You can fill these using the command
```shell
load_routingkit_unweighted_graph first_out.bin head.bin
```
as mentioned in my first comment https://github.com/kit-algo/InertialFlowCutter/issues/8#issuecomment-653438057.
All commands in the console do 'something' with that graph.

So a workflow to get an ordering could look like this
```shell
load_routingkit_unweighted_graph first_out.bin head.bin
reorder_nodes_in_kahip_nested_dissection_order 0.2
save_routingkit_node_permutation_since_last_load order.bin
```
